### ISSUE TITLE
Не поддерживается 

### ISSUE THREAD

**Issue by Merlin-Legend** [andrewz1/pixel-mdm-patch#1]
Здравствуйте. Установил ваш мод, но в Азербайджане не работает. Как я могу вам помочь в этом? Хотелось бы чтобы наша страна была. У нас 3 оператора и скорее всего настройки должны совпадать с СНГ.

**Comment by andrewz1** [comment]
@Merlin-Legend добавил в версии 1.4 - проверяйте

**Comment by Merlin-Legend** [comment]
> @Merlin-Legend добавил в версии 1.4 - проверяйте

Спасибо. Обновил ничего не изменилось.

**Comment by Merlin-Legend** [comment]
Работает. Спасибо 🤗

**Comment by andrewz1** [comment]
@Merlin-Legend если вы искали VoLTE - это не тот модуль что нужен вам. этот модуль исправляет агрегацию частот для стран, где Pixel на базе процессоров Tensor не продается официально. Для включения VoLTE вам нужен PixelIMS.
